### ISSUE TITLE
I'm just confused lol

### ISSUE THREAD

**Issue by sherpascott** [cassiancc/Item-Descriptions#3]
So when adding descriptions to a mod, it says to open the mod's language file. Does this mean I have to edit the mod itself, or can I use a resourcepack or datapack or something? Sorry I'm noob

**Comment by cassiancc** [comment]
No worries! Yep, a resource pack will work. I have an example resource pack on GitHub: https://github.com/cassiancc/Mod-Descriptions

**Comment by sherpascott** [comment]
Awesome! Thank you! I will be working on descriptions for quark, supplementaries, and Alex mobs. If I get them figured out how do I give them to you for the community creations?

**Comment by cassiancc** [comment]
You can fork Mod Descriptions, add the files, and send it in as a Pull Request here on GitHub, or just send the files and I'll make sure you get credit.
